### PR TITLE
Add support for encoding to and decoding from byte arrays

### PR DESCRIPTION
**Pull request by samal-rasmussen**
This is a solution for https://github.com/mathiasbynens/utf8.js/issues/7

### CODE REVIEW

**Comment by samal84** [comment]
It seems the build is failing because the build server's js environment doesn't support the Uint8Array type. Should I add a commit with feature detection for Uint8Array?

**Comment by wayofthefuture** [comment]
+1

**Comment by samal-rasmussen** [comment]
I've fixed up this branch so it builds again. The implementation is a bit cleaner too.

**Comment by samal-rasmussen** [comment]
Time flies and TextEncoder/TextDecoder are now widely supported in js.

**Pull request closed without merging**
